### PR TITLE
Convert to SCSS for eyeglass support (gen-2)

### PR DESCRIPTION
**Pull request by stevetweeddale**
This is a workaround for https://github.com/sass/node-sass/issues/1192, and as such could be reverted once that issue is resolved.

But for now, it converts to the SCSS syntax, and so fixes https://github.com/lolmaus/breakpoint-slicer/issues/17

It also adds a `needs` line to the the eyeglass section of package.json, because I was getting messages to tell me it should have one.

### CODE REVIEW

**Comment by jackw** [comment]
Can I ask why this PR was never merged into the project? Would be great to see this project fully compatible with node sass and eyeglass.

**Comment by lolmaus** [comment]
Hi!

I'm sorry I've been neglecting this for so long.

If this is still actual, can you please outline all the steps required for Eyeglass?

**Comment by stevetweeddale** [comment]
We've been using my fork in production for a couple of years now! I've just looked and:

*  sass/node-sass#1192 still hasn't been fixed, so converting to scss syntax is still a valid workaround
*  It doesn't look like the target 'gen-2' branch has had any dev since this PR was raised, so as far as I can tell this is still current.

If you're talking about how you would test eyeglass support you'd need to:

1.  Include eyeglass and your newly eyeglass-compatible npm module in your package.json. eg we're using:

```js
"devDependencies": {
  "breakpoint-slicer": "github:stevetweeddale/breakpoint-slicer",
  "eyeglass": "^0.8.3",
}
```
2. [Include eyeglass in your node-sass build process somehow](https://github.com/sass-eyeglass/eyeglass#building-sass-files-with-eyeglass-support)
3. `@import 'breakpoint-slicer';` in your sass and you're away.

**Comment by lolmaus** [comment]
Thank you for clarifications. :bow:

I'll look into this, can't say when, though. 😔

**Comment by lolmaus** [comment]
Thank you for your effort.

I've released a new version of Breakpoint Slicer: a complete rewrite, in scss, with support for Sass Modules and hopefully eyeglass.

I haven't tested eyeglass support, though. PRs welcome and I promise I deal with incoming PRs within a week.

**Pull request closed without merging**
